version: 2
jobs:
  node:
    working_directory: ~/eve/demo/eve-ui
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout:
          path: ~/eve
      # install top level npm dependencies
      - restore_cache:
          name: Restore Meteor Cache
          key: meteor-cache-{{ checksum ".meteor/release" }}
      - restore_cache:
          name: Restore NPM Cache
          key: npm-cache-{{ checksum "~/eve/package-lock.json" }}
      - restore_cache:
          name: Restore Meteor Package Cache
          key: packages-cache-{{ checksum ".meteor/versions" }}
      - restore_cache:
          name: Restore Node cache
          key: node-app-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
          working_directory: ~/eve
      - run:
          command: npm install truffle
          working_directory: ~/eve
      - save_cache:
          name: Save NPM Cache
          key: npm-cache-{{ checksum "~/eve/package-lock.json" }}
          paths:
            - '~/.npm'
            - '~/eve/node_modules'
      # install meteor
      - run: curl https://install.meteor.com/ | sh
      - run: meteor npm install
      - save_cache:
          name: Save Meteor Cache
          key: meteor-cache-{{ checksum ".meteor/release" }}
          paths:
            - '~/.meteor'
      - save_cache:
          key: packages-cache-{{ checksum ".meteor/versions" }}
          paths:
            - './.meteor/local/build'
            - './.meteor/local/bundler-cache'
            - './.meteor/local/isopacks'
            - './.meteor/local/plugin-cache'
      # WebApp dependencies
      - save_cache:
          key: node-app-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - eve

  app:
    working_directory: ~/eve/demo/eve-ui
    docker:
      - image: circleci/node:8.9
      - image: trufflesuite/ganache-cli
    steps:
      - checkout:
          path: ~/eve
      - attach_workspace:
          at: ~/
      - run: ls -R ~/eve
      # deploy smart contracts to local ganache blockchain
      - run:
          command: ~/eve/node_modules/truffle/build/cli.bundled.js migrate --reset --network development
          working_directory: ~/eve
      - run: ls build/contracts
      - run:
          name: Run Test
          command: echo "There will be tests"
#            command: ./tests/acceptance_run

workflows:
  version: 2
  node-truffle-meteor:
    jobs:
      - node
      - app:
          requires:
            - node
